version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /app
    environment:
      - TZ=America/Lima
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./:/app

# 1. install dependencies
#    $ docker-compose run --rm app npm install
# 2. run service
#    $ docker-compose up -d

